export { createHrmsDb, checkDatabase, type HrmsDb } from "./shared/client";
export { captureQueryScript, queryCaptureGeneration, type CapturedQuery } from "./shared/query-script";
export { hrmsDbConfigSchema, toMssqlConfig, type HrmsDbConfig } from "./shared/config";
export { asIso } from "./shared/iso";

export {
  ancestorMenuIds,
  attachTabsToMenuTree,
  buildMenuAccessTree,
  buildTabAccessTree,
  collectExpandableKeys,
  menuKey,
  parseAccessKey,
  tabKey,
  type AccessNode,
  type AccessRow,
  type GrantFlag,
  type MenuAccessRow,
  type TabAccessRow,
  loadEmployeeAccess,
  type EmployeeAccess,
  type TabMasterCheck,
  type TenantRoleOption,
  assignUserRole,
  grantRevokeUserAccess,
  listUserPageRows,
  listUserRolePreview,
  menuIdsForGrant,
  type GrantRevokeMode,
  type TabRight,
} from "./employee/access";

export {
  requireResolvedEmployee,
  resolveEmployee,
  type ResolvedEmployee,
} from "./shared/employee";
export {
  searchEmployees,
  type EmployeeSearchHit,
  type EmployeeSearchResult,
} from "./employee/search";
export {
  listBusinessUnitEmployees,
  type BusinessUnitEmployee,
  type BusinessUnitEmployees,
} from "./employee/business-unit";
export { getEmployeeProfile, type EmployeeProfile } from "./employee/profile";
export {
  getEmployeeLoginInfo,
  listUnlockPreview,
  unlockUserAccount,
  type EmployeeLoginInfo,
  type FailedLoginAttempt,
} from "./employee/login";
export {
  getEmployeeLeaveBalances,
  type LeaveBalanceRow,
} from "./employee/leave";
export {
  listEmployeeApprovers,
  type EmployeeApproverPerson,
  type EmployeeApproverRow,
  type EmployeeApprovers,
} from "./employee/approvers";
export {
  EMPLOYEE_LIST_SECTION_COLUMNS,
  getEmployeeSectionCounts,
  SECTION_COUNT_SPECS,
  SECTION_RECORD_SPECS,
  isCrudSectionId,
  sectionRecordSpecForId,
  tableSpecFor,
  listSectionFormFields,
  listSectionRecords,
  listPendingSectionRecords,
  groupPendingSectionRecords,
  loadSectionRecordValues,
  previewSectionUpsertDiff,
  commitUpsertSectionRecord,
  commitDeleteSectionRecord,
  sectionTableSupportsDelete,
  checkExistInDatabase,
  checkUniqueInDatabase,
  type EmployeeListSectionField,
  type EmployeeSectionCount,
  type EmployeeSectionCountFields,
  type SectionCountSpec,
  type SectionRecordSpec,
  type SectionTableSpec,
  type SoftDeleteSpec,
  type SectionFormField,
  type SectionRecordRow,
  type PendingSectionDetail,
  type PendingSectionRow,
  type PendingSectionStatus,
  type SectionRecordValues,
  type SectionUpsertInput,
  type SectionDeleteInput,
  type DbRuleCheckResult,
} from "./employee/sections";
export {
  HISTORY_CHANGE_TYPES,
  HISTORY_SECTION_NAMES,
  HISTORY_SECTIONS,
  HISTORY_VIEW_TYPES,
  DEFAULT_HISTORY_LOOKBACK_DAYS,
  MAX_HISTORY_LOOKBACK_DAYS,
  compareTimeStampDesc,
  diffSnapshotSeries,
  displayOrNotSet,
  groupFieldChangesIntoEvents,
  isHistorySectionName,
  listHistorySectionOptions,
  loadEmployeeHistoryChanges,
  normalizeDisplayValue,
  resolveHistoryDateWindow,
  sectionIdForName,
  snapshotsToEvents,
  type CatalogueField,
  type DateWindow,
  type HistoryChangeEvent,
  type HistoryChangeField,
  type HistoryChangeResponse,
  type HistoryChangeType,
  type HistoryEditor,
  type HistorySectionDef,
  type HistorySnapshot,
  type HistoryViewType,
  type LoadEmployeeHistoryInput,
} from "./employee/history";

export {
  getDatabaseHealth,
  listEmployers,
  type EmployerListItem,
} from "./employer/picker";
export {
  MASTER_DATA_CATALOG,
  MASTER_DATA_GROUPS,
  commitMasterDataWrite,
  editableMasterDataColumns,
  filterMasterDataCatalog,
  filterMasterDataRows,
  getMasterDataEntry,
  listAvailableMasterData,
  listMasterDataRows,
  loadMasterDataPage,
  masterDataEmployerId,
  parseMasterDataValues,
  previewMasterDataWrite,
  requireMasterDataEntry,
  type MasterDataColumn,
  type MasterDataEntry,
  type MasterDataGroupId,
  type MasterDataLookupOption,
  type MasterDataPageData,
  type MasterDataRow,
  type MasterDataValue,
  type MasterDataWriteMode,
} from "./employer/master-data";
export {
  browseDataFixTable,
  browseOrderColumns,
  commitDataFix,
  commitDataFixBatch,
  dataFixWriteBlock,
  loadDataFixColumn,
  parseDataFixLiteral,
  planColumnFilters,
  planDataFixWrite,
  previewDataFix,
  rankColumnHits,
  searchDataFixColumns,
  searchDataFixTables,
  type ColumnFilterInput,
  type DataFixBrowse,
  type DataFixCellEdit,
  type DataFixColumnFacts,
  type DataFixColumnHit,
  type DataFixColumnTarget,
  type DataFixTableHit,
  type DataFixPlan,
  type DataFixPreview,
  type DataFixRequest,
} from "./employer/data-fix";
export {
  assertSelectOnly,
  listTables,
  listTableColumns,
  getTableDefinition,
  listSearchTargets,
  searchValueInTables,
  searchValueExistence,
  listModules,
  getModuleDefinition,
  findScriptObject,
  findScriptObjectKinds,
  previewTableRows,
  executeSelect,
  executeFunction,
  parseQualifiedTable,
  qualifyTableName,
  type ExploreColumn,
  type ExploreSearchInput,
  type ExploreSearchMode,
  type ExploreSearchTableResult,
  type ExploreTable,
  type TableDefinition,
  type SearchTarget,
  type ExistenceTableResult,
  type ExistenceSearchInput,
  type ModuleKind,
  type ScriptObjectKind,
  type ModuleSummary,
  type ModuleDefinition,
  type PreviewTableRowsInput,
  type PreviewTableRowsResult,
  type ExecuteSelectInput,
  type ExecuteSelectResult,
  type ExecuteFunctionInput,
  type ExecuteFunctionResult,
} from "./dbs";
export {
  CUSTOMER_SETTING_CATEGORIES,
  CUSTOMER_SETTING_CATEGORY_IDS,
  CUSTOMER_SETTING_FIELDS,
  CUSTOMER_SETTING_FIELD_BY_KEY,
  compactJsonSetting,
  decodeSettingValue,
  diffCustomerSettingPatch,
  encodeSettingValue,
  fieldsForCategory,
  formatPreviewValue,
  getCustomerSettingCategory,
  getCustomerSettings,
  getEmployerSettings,
  isCustomerSettingCategoryId,
  listLicensedModules,
  parseCategoryPatch,
  previewCustomerSettingsPatch,
  requireSettingField,
  settingValuesEqual,
  updateCustomerSettingsCategory,
  type CustomerSettingCategory,
  type CustomerSettingCategoryId,
  type CustomerSettingField,
  type CustomerSettingGroup,
  type CustomerSettingSelectOption,
  type CustomerSettingTable,
  type CustomerSettingUiValue,
  type CustomerSettingValueType,
  type CustomerSettingsPatchInput,
  type CustomerSettingsRow,
  type EmployerSettings,
  type LicensedModule,
} from "./employer/settings";
export {
  asFieldFlag,
  compareEmployerFieldsToTemplate,
  diffFieldRow,
  formatFieldRowReplaySql,
  formatValidationRuleReplaySql,
  getEmployerFieldRow,
  getEmployerFieldValidationPreview,
  getFieldTypeName,
  KNOWN_FIELD_ENTITIES,
  listEmployerFields,
  listFieldTemplate,
  listFieldTypes,
  parseFieldRowPatch,
  fieldRowPatchSchema,
  parseValidationRuleJson,
  updateEmployerFieldRow,
  updateEmployerFieldValidationRule,
  VALIDATION_RULE_MAX_LENGTH,
  validateValidationRuleValue,
  type FieldCatalogRow,
  type FieldCompareRow,
  type FieldCompareStatus,
  type FieldRowCurrent,
  type FieldRowPatch,
  type FieldTypeOption,
  type ValidationRuleParseResult,
} from "./employer/fields";

export {
  listRolePageGrants,
  listRoles,
  type RolePageGrant,
  type RoleRow,
} from "./employer/roles";

export {
  EXPIRED_AFTER_DAYS,
  IMAGE_SECTION_ID,
  IMAGE_SECTION_NAME,
  PIPELINE_STEPS,
  STUCK_AFTER_HOURS,
  UPLOAD_CATEGORY_ID,
  UPLOAD_ERROR_CLASSES,
  UPLOAD_TYPE_DB,
  UPLOAD_TYPE_KEYS,
  UPLOAD_TYPE_LABELS,
  compareUploadHeaders,
  creationExcludedFieldNames,
  isMissingObjectError,
  missingObjectName,
  getCreationFinalize,
  getCreationStagingRow,
  getUpload,
  getUploadBatch,
  getUploadLiveRow,
  listCreationStaging,
  listUploadBatches,
  listUploadCatalog,
  listUploadCountries,
  listUploadExecutionErrors,
  listUploadRowErrors,
  listUploadSectionData,
  listUploads,
  parseUploadTypeKey,
  validationRuleNames,
  type CreationFinalize,
  type CreationStagingRow,
  type CreationStagingSummary,
  type UploadBatchDetail,
  type UploadBatchRow,
  type UploadCatalog,
  type UploadCatalogField,
  type UploadCatalogSection,
  type UploadCountryOption,
  type UploadDetail,
  type UploadErrorClass,
  type UploadExecutionError,
  type UploadHeaderMismatch,
  type UploadListFilters,
  type UploadListItem,
  type UploadLiveRow,
  type UploadRowError,
  type UploadRowErrorResult,
  type UploadSectionData,
  type UploadSectionDataRow,
  type UploadSectionRollup,
  type UploadTypeKey,
} from "./employer/uploads";

export {
  EMAIL_MODULE_LABELS,
  EMAIL_MODULES,
  EMAIL_PAGE_SIZE,
  EMAIL_STATUSES,
  INBOX_PAGE_SIZE,
  listEmailNotifications,
  listPendingInbox,
  normalizeEmailStatus,
  parseEmailModuleKey,
  parseEmailStatus,
  type EmailModuleKey,
  type EmailNotificationFilters,
  type EmailNotificationList,
  type EmailNotificationRow,
  type EmailStatus,
  type EmailStatusCount,
  type InboxPerson,
  type InboxSide,
  type PendingInboxCategory,
  type PendingInboxFilters,
  type PendingInboxList,
  type PendingInboxRow,
  type PendingInboxTypeCount,
} from "./employer/notifications";

export {
  BUILTIN_WORKFLOW_ROLES,
  actorFromName,
  createWorkflowHeader,
  emptyWorkflowTree,
  encodeWorkflowDefinitionTree,
  flattenWorkflowDetails,
  getWorkflow,
  getWorkflowSettings,
  getWorkflowWritePreview,
  isWorkflowPartial,
  listMappablePages,
  listWorkflowBusinessUnits,
  listWorkflowCollisions,
  listWorkflowGroups,
  listWorkflowLocations,
  listWorkflowPages,
  listChangeRequests,
  listEmployeeChangeRequests,
  listConfiguredApprovers,
  listWorkflows,
  lookupWorkflowRoleIds,
  parseWorkflowDefinitionTree,
  pendingApproverFlag,
  resolveApplyValue,
  coerceBitApplyValue,
  omitIsDeleteOnInsert,
  forceShowOneOnInsert,
  resolveWorkflowStatus,
  updateWorkflowHeader,
  updateWorkflowTree,
  workflowRoleCode,
  getChangeRequest,
  getChangeRequestWritePreview,
  decideChangeRequest,
  buildApplyPlan,
  changeRequestStatus,
  APPLY_TABLES,
  CHANGE_REQUEST_STATUSES,
  type ChangeRequestApprover,
  type ChangeRequestDecision,
  type ChangeRequestDetail,
  type ChangeRequestDetailRow,
  type ChangeRequestListItem,
  type ChangeRequestQueueRow,
  type ChangeRequestStatus,
  type ChangeRequestWriteInput,
  type ConfiguredApproverGroup,
  type ConfiguredApproverPerson,
  type FlattenedWorkflowDetail,
  type WorkflowActor,
  type WorkflowCollision,
  type WorkflowDefinition,
  type WorkflowDefinitionStatus,
  type WorkflowDetailRow,
  type WorkflowGroupMember,
  type WorkflowGroupRow,
  type WorkflowHeaderInput,
  type WorkflowLevel,
  type WorkflowListItem,
  type WorkflowPageCatalogRow,
  type WorkflowPageMapping,
  type WorkflowRoleCode,
  type WorkflowScopeOption,
  type WorkflowSettings,
  type WorkflowTree,
} from "./employer/workflows";
