-- =============================================================================
-- diagnose-menu-setup-by-employer.sql
--
-- Purpose:  Given a menu NAME and an EMPLOYER, show which of the four places a
--           left-menu item's setup can be incomplete is actually missing:
--             1. Master row      - tMenuDetails
--             2. Hierarchy link  - TMenuHierarchy
--             3. Dynamic Menu tab cache - TDynamicMenuHierarchy (the XML blob
--                behind RoleManagement.aspx's "Dynamic Menu" tab)
--             4. Access grants   - TRolePagesMapping / TUSerPagesMapping
--           Unlike diagnose-menu-tab-access.sql (which answers "why can't THIS
--           EMPLOYEE see it"), this answers "why doesn't this menu exist for
--           THIS EMPLOYER at all" - the question an admin asks when a menu was
--           created in the DB but never shows up anywhere for that tenant,
--           including the admin hierarchy editor itself.
--
-- Root cause logic (confirmed against the actual stored procedures and the
-- RoleManagement.aspx.cs code-behind):
--   - sp_GetDynamicMenuItems.sql:57-122 (end-user left menu at runtime): an
--     item shows if EITHER the employee's RoleID has a row in
--     TRolePagesMapping OR the employee's UserID has a row in
--     TUSerPagesMapping, for that MenuId (called "PageId" there) - AND
--     Employerid matches exactly across TUsers/TMenuHierarchy/tMenuDetails -
--     AND tMenuDetails.ISActive = 1.
--   - sp_GetDynamicMenuHierarchy.sql (the "Dynamic Menu" tab on
--     RoleManagement.aspx): does NOT query TMenuHierarchy/tMenuDetails live.
--     It returns a CACHED XML SNAPSHOT from TDynamicMenuHierarchy.
--     DynamicMenuXML for the given Employerid; if that Employerid has ZERO
--     rows there, it falls back to the Employerid = 0 row's cached XML.
--   - That cache is only ever regenerated by RoleManagement.aspx.cs's
--     btnDynamicUpdate_Click -> sp_InsertDynamicMenuHierarchy, which rebuilds
--     TDynamicMenuHierarchy/TMenuHierarchy/tMenuDetails from whatever nodes
--     are currently in the RadTreeViewDynamicMenu tree control on submit. A
--     menu row inserted directly into tMenuDetails/TMenuHierarchy (script,
--     migration, ad-hoc INSERT) never touches TDynamicMenuHierarchy, so the
--     Dynamic Menu tab keeps showing the old cached tree - the new item is
--     genuinely in the database but invisible on that page until the cache
--     is regenerated (normally by adding it through that tab's tree UI and
--     clicking Submit).
--   - New menu rows are conventionally created first at Employerid = 0 (the
--     global template): sp_InsertDynamicMenuHierarchy.sql:151-187 copies
--     NavigateURL/PageName/iconname for every node from the Employerid = 0
--     row when rebuilding tMenuDetails for a specific tenant. A menu that
--     only exists at a non-zero Employerid, never at 0, is a likely gap in
--     itself.
--
-- When to use: a menu was created in the database, but for a given employer
--           it doesn't show in the Dynamic Menu tab hierarchy (admin side)
--           and/or never reaches any employee's left menu (runtime side).
--           You have a menu NAME and an EMPLOYER, not a specific employee.
--
-- Inputs:   @MenuName   (required unless @MenuId is set) - LIKE pattern,
--                       e.g. '%Leave%'. Matched across ALL employers so you
--                       can see where the name does/doesn't exist.
--           @MenuId     (optional) - set this instead of @MenuName if you
--                       already know the exact MenuId.
--           @EmployerId (required) - the tenant to diagnose.
--
-- Type:     Read-only (SELECT only); uses local #temp/table variables (no
--           permanent objects, nothing dropped or altered).
-- =============================================================================

DECLARE @MenuName   VARCHAR(200) = '%Leave%';  -- <<< REQUIRED unless @MenuId is set
DECLARE @MenuId     INT          = NULL;       -- <<< optional: set this instead of @MenuName
DECLARE @EmployerId INT          = 11;         -- <<< REQUIRED: the tenant to diagnose

-- ---------------------------------------------------------------------------
-- Result set 0: name resolution - every tMenuDetails row matching @MenuName
-- (or @MenuId), across ALL employers. Shows at a glance whether the name
-- exists at the Employerid = 0 template, at the target tenant, at neither,
-- or only at some other tenant entirely.
-- ---------------------------------------------------------------------------
SELECT
    'Name resolution' AS DatasetType,
    md.MenuId,
    md.MenuName,
    md.Employerid,
    md.ISActive,
    md.NavigateURL,
    CASE
        WHEN md.Employerid = 0 THEN 'Global template'
        WHEN md.Employerid = @EmployerId THEN 'Target tenant'
        ELSE 'Other tenant'
    END AS RowRole
FROM tMenuDetails md WITH (NOLOCK)
WHERE (@MenuId IS NOT NULL AND md.MenuId = @MenuId)
   OR (@MenuId IS NULL AND md.MenuName LIKE @MenuName)
ORDER BY CASE WHEN md.Employerid = 0 THEN 0 WHEN md.Employerid = @EmployerId THEN 1 ELSE 2 END, md.Employerid;

-- Pick the MenuId to diagnose: prefer an exact @MenuId, else prefer the
-- template (Employerid = 0) row for the matched name, else the target
-- tenant's own row, else whatever matched first.
DECLARE @Lv_MenuId INT = @MenuId;
IF @Lv_MenuId IS NULL
BEGIN
    SELECT TOP 1 @Lv_MenuId = md.MenuId
    FROM tMenuDetails md WITH (NOLOCK)
    WHERE md.MenuName LIKE @MenuName
    ORDER BY CASE WHEN md.Employerid = 0 THEN 0 WHEN md.Employerid = @EmployerId THEN 1 ELSE 2 END, md.Employerid;
END

IF @Lv_MenuId IS NULL
BEGIN
    RAISERROR('No tMenuDetails row matches @MenuName/@MenuId anywhere - it was never inserted into the menu master at all. Check with whoever created it before proceeding.', 16, 1);
    RETURN;
END

-- ---------------------------------------------------------------------------
-- Result set 1: master row (tMenuDetails) - template (0) vs target tenant.
-- ---------------------------------------------------------------------------
SELECT
    'Master row (tMenuDetails)' AS DatasetType,
    src.Label,
    md.MenuId,
    md.MenuName,
    md.ISActive,
    md.NavigateURL,
    md.PageName,
    CASE
        WHEN md.MenuId IS NULL THEN 'MISSING - no tMenuDetails row for this Employerid'
        WHEN md.ISActive = 0 THEN 'INACTIVE - hides it for every role/user at this tenant'
        ELSE 'OK'
    END AS LikelyCause
FROM (SELECT 0 AS Employerid, 'Global template (0)' AS Label
      UNION ALL SELECT @EmployerId, 'Target tenant') src
LEFT JOIN tMenuDetails md WITH (NOLOCK)
    ON md.MenuId = @Lv_MenuId AND md.Employerid = src.Employerid;

-- ---------------------------------------------------------------------------
-- Result set 2: hierarchy link (TMenuHierarchy) - template (0) vs target
-- tenant. Also flags an orphaned ParentMenuId (a parent that itself has no
-- tMenuDetails row at the same Employerid - hides the whole branch).
-- ---------------------------------------------------------------------------
SELECT
    'Hierarchy link (TMenuHierarchy)' AS DatasetType,
    src.Label,
    mh.MenuId,
    mh.ParentMenuId,
    mh.parentseq,
    CASE
        WHEN mh.MenuId IS NULL THEN 'MISSING - no TMenuHierarchy row for this Employerid'
        WHEN mh.ParentMenuId IS NOT NULL AND parentmd.MenuId IS NULL
            THEN 'ORPHANED PARENT - ParentMenuId ' + CAST(mh.ParentMenuId AS VARCHAR(20)) + ' has no tMenuDetails row at Employerid ' + CAST(src.Employerid AS VARCHAR(20))
        ELSE 'OK'
    END AS LikelyCause
FROM (SELECT 0 AS Employerid, 'Global template (0)' AS Label
      UNION ALL SELECT @EmployerId, 'Target tenant') src
LEFT JOIN TMenuHierarchy mh WITH (NOLOCK)
    ON mh.MenuId = @Lv_MenuId AND mh.Employerid = src.Employerid
LEFT JOIN tMenuDetails parentmd WITH (NOLOCK)
    ON parentmd.MenuId = mh.ParentMenuId AND parentmd.Employerid = src.Employerid;

-- ---------------------------------------------------------------------------
-- Result set 3: Dynamic Menu tab cache (TDynamicMenuHierarchy). Replicates
-- sp_GetDynamicMenuHierarchy's fallback-to-0 logic, then shreds whichever
-- XML blob is actually served to check whether this MenuId is in it.
-- ---------------------------------------------------------------------------
DECLARE @Lv_TenantCacheCount INT;
SELECT @Lv_TenantCacheCount = COUNT(1) FROM TDynamicMenuHierarchy WITH (NOLOCK) WHERE Employerid = @EmployerId;

DECLARE @Lv_EffectiveEmployerid INT = CASE WHEN @Lv_TenantCacheCount = 0 THEN 0 ELSE @EmployerId END;
DECLARE @Lv_EffectiveXml VARCHAR(MAX);
SELECT TOP 1 @Lv_EffectiveXml = DynamicMenuXML
FROM TDynamicMenuHierarchy WITH (NOLOCK)
WHERE Employerid = @Lv_EffectiveEmployerid
ORDER BY Transid DESC;

DECLARE @Lv_Xml XML = TRY_CAST(@Lv_EffectiveXml AS XML);
DECLARE @Lv_InCachedTree BIT = 0;
IF @Lv_Xml IS NOT NULL
BEGIN
    SELECT @Lv_InCachedTree = 1
    FROM @Lv_Xml.nodes('//Node') AS T(x)
    WHERE x.value('@Value', 'VARCHAR(50)') = CAST(@Lv_MenuId AS VARCHAR(50));
END

SELECT
    'Dynamic Menu tab cache (TDynamicMenuHierarchy)' AS DatasetType,
    @EmployerId AS TargetEmployerid,
    @Lv_TenantCacheCount AS TenantHasOwnCacheRow,
    @Lv_EffectiveEmployerid AS EffectiveCacheSourceEmployerid,
    CASE WHEN @Lv_Xml IS NULL THEN 'N/A - no cache row or unparsable XML' ELSE CASE WHEN @Lv_InCachedTree = 1 THEN 'Y' ELSE 'N' END END AS MenuIdFoundInCachedTree,
    CASE
        WHEN @Lv_Xml IS NULL
            THEN 'No TDynamicMenuHierarchy row for Employerid ' + CAST(@Lv_EffectiveEmployerid AS VARCHAR(20)) + ' (or its XML is unparsable) - the Dynamic Menu tab has nothing to render for this source.'
        WHEN @Lv_InCachedTree = 0
            THEN 'STALE CACHE - MenuId ' + CAST(@Lv_MenuId AS VARCHAR(20)) + ' exists in tMenuDetails/TMenuHierarchy but NOT in the cached tree (source: Employerid ' + CAST(@Lv_EffectiveEmployerid AS VARCHAR(20)) + '). This is almost certainly why it is missing from the Dynamic Menu tab: it was added directly to the tables, not through the tab''s tree-edit-then-Submit flow, so the cache was never regenerated.'
        ELSE 'OK - present in the cached tree that RoleManagement.aspx will render for this tenant.'
    END AS LikelyCause;

-- ---------------------------------------------------------------------------
-- Result set 4: access grants (TRolePagesMapping / TUSerPagesMapping) at
-- this tenant, for this MenuId. Informational for the admin-hierarchy
-- question, but tells you whether end users would ALSO be blocked once the
-- hierarchy/cache issues above are fixed.
-- ---------------------------------------------------------------------------
SELECT
    'Access grants at this tenant' AS DatasetType,
    @EmployerId AS Employerid,
    @Lv_MenuId AS MenuId,
    (SELECT COUNT(*) FROM TRolePagesMapping WITH (NOLOCK) WHERE PageId = @Lv_MenuId AND Employerid = @EmployerId) AS RoleGrantRows,
    (SELECT COUNT(*) FROM TUSerPagesMapping WITH (NOLOCK) WHERE PageId = @Lv_MenuId AND Employerid = @EmployerId) AS UserGrantRows,
    CASE
        WHEN (SELECT COUNT(*) FROM TRolePagesMapping WITH (NOLOCK) WHERE PageId = @Lv_MenuId AND Employerid = @EmployerId) = 0
         AND (SELECT COUNT(*) FROM TUSerPagesMapping WITH (NOLOCK) WHERE PageId = @Lv_MenuId AND Employerid = @EmployerId) = 0
            THEN 'No role or user at this tenant has been granted this MenuId yet - even once it shows in the hierarchy, no employee will see it in their left menu until a role/user grant is added.'
        ELSE 'At least one role/user grant exists at this tenant for this MenuId.'
    END AS LikelyCause;
