export {
  FLOAT_MENU_ITEMS,
  FAB_SIZE,
  DRAG_THRESHOLD_PX,
  MENU_GAP_PX,
  MENU_ESTIMATED_WIDTH,
  MENU_ESTIMATED_HEIGHT,
  buildRequestForAction,
  clampFabPosition,
  defaultFabPosition,
  isDragGesture,
  isFloatMenuActionId,
  normalizeFabPosition,
  resolveFabPosition,
  resolveMenuPlacement,
  shouldMountFloatMenu,
  mountFloatMenu,
  unmountFloatMenu,
} from "./float-menu";
export type {
  FabPosition,
  FloatMenuActionId,
  FloatMenuController,
  FloatMenuIconName,
  FloatMenuItem,
  MenuPlacement,
  MountFloatMenuOptions,
} from "./float-menu";
