DECLARE 
    @RegisterAssetId INT = 0,
    @CategoryId INT = 1402,
    @AssetCode VARCHAR(100) = 'H2',
    @DateOfPurchase DATETIME = '2024-02-24',
    @VendorName VARCHAR(100) = 'Dell',
    @VendorDetails VARCHAR(100) = NULL,
    @AssetCost DECIMAL(9,2) = 2000,
    @WarrantyEndDate DATETIME = '2026-02-24',
    @Brand VARCHAR(100) = 'Dell',
    @ModelSeries VARCHAR(100) = 'ABC',
    @SerialNumber VARCHAR(100) = 'ABCDEF',
    @DeviceConfiguration VARCHAR(100) = '123456',
    @HostName VARCHAR(100) = '',
    @AssetStatus VARCHAR(100) = 'Not Working',
    @AssetDescription VARCHAR(100) = NULL,
    @FilePath VARCHAR(100) = '',
    @Comments VARCHAR(100) = '',
    @EffectiveDate DATETIME = NULL,
    @EffectiveBy VARCHAR(100) = NULL,
    @IsActive BIT = 0,
    @IsDelete VARCHAR(100) = '',
    @CreatedBy INT = 1431,
    @EmployerId INT = 10,
    @CurrencyCodeId INT = 99;

EXEC USP_ASSET_InsertRegisterAsset
        @RegisterAssetId,
        @CategoryId,
        @AssetCode,
        @DateOfPurchase,
        @VendorName,
        @VendorDetails,
        @AssetCost,
        @WarrantyEndDate,
        @Brand,
        @ModelSeries,
        @SerialNumber,
        @DeviceConfiguration,
        @HostName,
        @AssetStatus,
        @AssetDescription,
        @FilePath,
        @Comments,
        @EffectiveDate,
        @EffectiveBy,
        @IsActive,
        @IsDelete,
        @EmployerId,
        @CreatedBy,
        @CurrencyCodeId;
        