DECLARE @AdvanceRequestDetailId INT = NULL,
        @EmployerId INT = 10,
        @EmployeeId INT = 1430,
        @TravelRequestId INT = 1294,
        @CostCenterId INT = 13,
        @ProjectId INT = 2001,
        @TotalAdvanceRequested DECIMAL(9,2) = NULL,
        @PaymentModeId INT = 371,
        @EmployeeComments VARCHAR(MAX) = 'Hanh Test',
        @RequestedBy INT = NULL,
        @IsSubmitted BIT = 1,
        @CreatedBy INT = 1430;

EXEC Sp_Advances_InsAdvanceReqByEmployee @AdvanceRequestDetailId,
    @EmployerId,
    @EmployeeId,
    @TravelRequestId,
    @CostCenterId,
    @ProjectId,
    @TotalAdvanceRequested,
    @PaymentModeId,
    @EmployeeComments,
    @RequestedBy,
    @IsSubmitted,
    @CreatedBy
