DECLARE @LevelWiseExpenseDetailsID INT = 0,
    @EmployerID INT = 10,
    @ExpenseTypeID INT = 701,
    @SubExpenseTypeID INT = 201,
    @LevelID VARCHAR(MAX) = '353,23,357,358,359',
    @currencyId INT = 96,
    @MaxLimit DECIMAL = 100000.00,
    @IsActive BIT = 1,
    @IsAutoApprove BIT = 0,
    @LoginUserID INT = 1430,
    @SelectedWorkFlow VARCHAR = NULL,
    @WorkflowSelectedLevel VARCHAR = NULL,
    @BUID VARCHAR = NULL,
    @RoleID VARCHAR = NULL,
    @DesignationID VARCHAR = NULL,
    @WorkLocationID VARCHAR = NULL,
    @BaseLocationID VARCHAR = NULL,
    @EmployeeID VARCHAR = NULL,
    @Sub_SubExpenseTypeID INT = NULL,
    @EffectiveFrom DATETIME = '2024-05-31',
    @FromCityID INT = NULL,
    @ToCityID INT = NULL,
    @Distance FLOAT = NULL,
    @DistanceUnit VARCHAR = NULL,
    @IsFlatRate BIT = NULL;


EXEC usp_InsUpdt_LevelWiseExpenseDetails
    @LevelWiseExpenseDetailsID,
    @EmployerID,
    @ExpenseTypeID,
    @LevelID,
    @MaxLimit,
    @IsActive,
    @LoginUserID,
    @SubExpenseTypeID,
    @currencyId,
    @IsAutoApprove,
    @SelectedWorkFlow,
    @WorkflowSelectedLevel,
    @BUID,
    @RoleID,
    @DesignationID,
    @WorkflowSelectedLevel,
    @BaseLocationID,
    @EmployeeID,
    @Sub_SubExpenseTypeID,
    @EffectiveFrom,
    @FromCityID,
    @ToCityID,
    @Distance,
    @DistanceUnit,
    @IsFlatRate